version: '3.8'

services:
  line-separator-bot:
    build: .
    container_name: line-separator-bot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
